# Generated by Django 5.0.4 on 2024-06-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_banner',
        ),
    ]
