# Generated by Django 5.0.4 on 2024-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_remove_product_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
