# Generated by Django 5.0.4 on 2024-06-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_product_brand_product_item_height_product_item_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
