# Generated by Django 5.0.4 on 2024-06-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_percentage_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_amount_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, to='product_module.category')),
                ('products', models.ManyToManyField(blank=True, to='product_module.product')),
            ],
        ),
    ]
