# Generated by Django 5.0.4 on 2024-06-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=10),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
