# Generated by Django 5.0.4 on 2024-06-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
