# Generated by Django 5.0.4 on 2024-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_banner_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
